### PR TITLE
pyside wheels for cinema4d 2023.2

### LINKED ISSUE #1: Wheels are not compatible with Cinema 4D 2023.2 (Python 3.10)
Since Maxon decided to do an update in the latest (2023.2) version, the wheels are not compatible anymore. 
I'm willing to contribute to this repo but i lack the knowledge to build the .whl files. Could you point me in the right direction ?
Thanks in advance :)

### PR DESCRIPTION
**Pull request by blockinhead**
in cinema4d 2023.2 python was updated to 3.10, so here are new wheel

### CODE REVIEW

**Comment by danbradham** [comment]
Thank you so much for the contribution! This has been on my backlog since 2023.3 was released.

Was this built with qwebengine support?

**Comment by blockinhead** [comment]
i'm not sure about it, i havn't seen any special options to build it with or without webengine, but  
```
dir /b Qt5WebEngine*  
Qt5WebEngine.dll  
Qt5WebEngineCore.dll  
Qt5WebEngineWidgets.dll  
```
also, i didn't test it with shotgun toolkit, but c4dpy can start pyside scripts, i've tested that.

**Comment by blockinhead** [comment]
```
λ dir /b *webengine*
Qt5WebEngine.dll
Qt5WebEngineCore.dll
Qt5WebEngineWidgets.dll
QtWebEngine.cp310-win_amd64.pyd
QtWebEngine.pyi
QtWebEngineCore.cp310-win_amd64.pyd
QtWebEngineCore.pyi
QtWebEngineProcess.exe
QtWebEngineWidgets.cp310-win_amd64.pyd
QtWebEngineWidgets.pyi
```

**Comment by danbradham** [comment]
Okay cool, I'm going to try it out and merge if sgtk is functioning. Typically that's fine when it works through c4dpy.

**Comment by danbradham** [comment]
Seems to be working great. I think the sgtk app for cinema4d may need an update but this build seems to be fine itself.

Thanks again @blockinhead !

**Comment by blambright** [comment]
You guys came in clutch for me. I can confirm that the wheels work well. Thanks @blockinhead and @danbradham !!

**Pull request merged**
